- name: Deploy MySQL related sources
  hosts: webapp
  become: true
  tasks:
    - name: Copy specific SQL files to the target server
      ansible.builtin.copy:
        src: "../webapp/sql/{{ item }}"
        dest: "/home/isucon/webapp/sql/{{ item }}"
        owner: isucon
        group: isucon
        mode: "0755"
      with_items:
        - "0-init.sql"
        - "1-schema.sql"
        - "2-master-data.sql"
        - "init.sh"
      notify: restart_mysql

  handlers:
    - name: restart_mysql
      ansible.builtin.service:
        name: mysql
        state: restarted
